### ISSUE TITLE
Training dataset

### ISSUE THREAD

**Issue by yashjain1129** [amazon-science/ReFinED#3]
Can you please share the processed wikipedia training dataset?

**Comment by tayoola** [comment]
Yes, we will release this in the next few weeks. Thanks.

**Comment by tayoola** [comment]
Hi, the dataset is now downloaded when you run the `train.py` script (https://github.com/amazon-science/ReFinED/blob/main/src/refined/training/train/train.py). You can also regenerate, the dataset if you need an up-to-date version of the dataset by running our `preprocess_all.py` script. Hope this helps. Thanks.

**Comment by yashjain1129** [comment]
Thank you @tayoola.
