### ISSUE TITLE
Code for Entity_Linking

### ISSUE THREAD

**Issue by vevake** [amazon-science/ReFinED#4]
Hi, Congratulations on your work. I am interested to experiment with the entity_linking part of this paper. Any details on when can we expect the code for it?

**Comment by robbohua** [comment]
Bump!

**Comment by tayoola** [comment]
Hi, thank you. We plan to release this code in the next few weeks.

**Comment by tayoola** [comment]
Hi, I have added the code for this and instructions are in the README https://github.com/amazon-science/ReFinED/blob/main/README.md.
