### ISSUE TITLE
Batch support at the time of inference

### ISSUE THREAD

**Issue by prashantkh198** [amazon-science/ReFinED#5]
The [process_text_batch](https://github.com/amazon-research/ReFinED/blob/main/src/refined/processor.py#L352) function is not implemented as of now. When can we expect it to be implemented? Is there any documentation that we can follow to implement it ourselves?

**Comment by tayoola** [comment]
Hi. We do not have an exact timeline on this. But we will add some documentation in the next commit, to make it easier for you to implement yourself. Thanks.

**Comment by tayoola** [comment]
Hi, this has been added here https://github.com/amazon-science/ReFinED/blob/main/src/refined/inference/processor.py#L197. Thanks.
