### ISSUE TITLE
Instructions for training a new model

### ISSUE THREAD

**Issue by tonydeep** [amazon-science/ReFinED#7]
Hi team, thanks for sharing your great work.
Could you please share your instructions for step-by-step preparing the Wikipedia dataset and training a new Wikipedia model.
Best,

**Comment by tayoola** [comment]
Hi, thanks. Yes, we will add instructions to the README in our next commit. Thanks.

**Comment by tayoola** [comment]
Hi tonydeep, we have added instructions for this in the README https://github.com/amazon-science/ReFinED/blob/main/README.md. Thanks.
